# Generated by Django 6.0.1 on 2026-01-29 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=200)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details_t', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_details',
            },
        ),
    ]
