# Generated by Django 6.0.1 on 2026-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='budget_mensile',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Budget mensile assegnato a questa categoria', max_digits=10),
        ),
    ]
