# Generated by Django 6.0.1 on 2026-02-06 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0002_categoria_budget_mensile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
