# Generated by Django 6.0.1 on 2026-02-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('note', models.TextField(blank=True, help_text="Note opzionali, es. 'ne valeva la pena'", null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spese', to='Categoria.categoria')),
            ],
            options={
                'db_table': 'spesa',
            },
        ),
    ]
