# Generated by Django 6.0.1 on 2026-02-06 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesa',
            name='descrizione',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spesa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
