# Generated by Django 6.0.1 on 2026-01-31 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giorni_presenze', '0001_initial'),
        ('partecipanti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stato', models.BooleanField(blank=True, default=True)),
                ('giorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giorni_presenze.giorno')),
                ('partecipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partecipanti.partecipante')),
            ],
        ),
    ]
