# Generated by Django 6.0.1 on 2026-01-26 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=200)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='project.project')),
            ],
            options={
                'db_table': 'projects_details',
            },
        ),
    ]
