# Generated by Django 6.0.1 on 2026-01-31 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partecipante',
            fields=[
                ('matricola', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_preautorizzata', models.EmailField(max_length=254, unique=True)),
                ('data_iscrizione', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partecipanti',
            },
        ),
    ]
