# Generated by Django 6.0.1 on 2026-01-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('descrizione', models.TextField(max_length=500)),
            ],
        ),
    ]
