# Generated by Django 6.0.1 on 2026-01-31 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id_giorno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('descrizione', models.TextField(max_length=500)),
            ],
        ),
    ]
