# Generated by Django 6.0.1 on 2026-01-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenatore', '0001_initial'),
        ('pokemon', '0002_alter_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='allenatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='allenatore.allenatore'),
        ),
    ]
