# Generated by Django 6.0.1 on 2026-01-22 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_allenatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='punti_salute',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sesso',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina'), ('N', 'Sconosciuto')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tipo_primario',
            field=models.CharField(choices=[('normale', 'Normale'), ('fuoco', 'Fuoco'), ('acqua', 'Acqua'), ('erba', 'Erba'), ('elettro', 'Elettro'), ('ghiaccio', 'Ghiaccio'), ('lotta', 'Lotta'), ('veleno', 'Veleno'), ('terra', 'Terra'), ('volante', 'Volante'), ('psico', 'Psico'), ('coleottero', 'Coleottero'), ('roccia', 'Roccia'), ('spettro', 'Spettro'), ('drago', 'Drago'), ('buio', 'Buio'), ('acciaio', 'Acciaio'), ('folletto', 'Folletto')], default='normale', max_length=20),
        ),
    ]
